### ISSUE TITLE
update_config.sh bug

### ISSUE THREAD

**Issue by the-braveknight** [RehabMan/Lenovo-U430-Touch-DSDT-Patch#4]
needs `sudo ./mount_efi.sh /` instead of `sudo mount_efi.sh /`

**Comment by RehabMan** [comment]
The script is only for my own use (I have not finished it).
I have my mount_efi.sh installed to /usr/bin.

**Comment by the-braveknight** [comment]
Okay but it might be very handy and useful for the others as well... :)

**Comment by RehabMan** [comment]
Yes, just too busy to finish it.  And I'm really debating about it since it is yet another script that allows the user "not to learn".

**Comment by the-braveknight** [comment]
Yeah you're right xD
